apiVersion: blueprints.cloud.google.com/v1alpha3
kind: ResourceHierarchy
metadata:
  name: root-hierarchy
  namespace: hierarchy # kpt-set: ${namespace}
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  config:
    - dev:
        $subtree: environment
    - prod:
        $subtree: environment
  parentRef:
    # This should match your organization ID
    external: "123456789012"
  subtrees:
    environment:
      - retail:
          - apps
          - data
      - finance:
          - commercial
